name: CI

on:
  push:
    branches:
      - main
    
      
env:
  DOCKER_USERNAME: kekgaugetswe  
  REPO: kekgaugetswe/doosy_api

jobs: 
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        with:
        # Fetch all commits   
          fetch-depth: 0
        
      - name: Sematic versioning
        id: versioning
        uses: PaulHatch/semantic-version@v4.0.2
        with: 
          branch: main
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGES"
          minor_pattern: "feat"
          format: "v${major}.${minor}.${patch}-prerealease${increment}"
      
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      
      #- name: Build and push Docker image
       # id:   docker_build
        #uses: docker/build-push-action@v2
       # with:
        #  push: true
          #tags:  ${{ secrets.DOCKER_HUB_USERNAME }}/doosyapiii:latest, ${{secrets.DOCKER_HUB_USERNAME }}/doosyapiii:${{ steps.versioning.outputs.version }}
         # file: Doosy.API/Dockerfile
        
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ env.REPO }}:latest,${{ env.REPO }}:${{ steps.versioning.outputs.version }}
          file: Doosy.API/Dockerfile
          
      - name: Create Release
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          release_name: ${{ steps.versioning.outputs.version }}
          prerelease: true
        
          
      
      
