name: deployment
on:
  push:
    tags:
      - 'v*'

env:
  DOCKER_USERNAME: kekgaugetswe
  REPO: kekgaugetswe/doosy_api

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all commits
          fetch-depth: 0

      - name: Set environment variables
        run: |
          cat >> $GITHUB_ENV << EOF
          VERSION=${GITHUB_REF##*/}
          EOF
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REPO }}:latest,${{ env.REPO }}:${{ env.VERSION }}
          file: Doosy.API/Dockerfile 
          
      - name: testing doosy-deploy ssh connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            #if [  "$(docker ps  -a -f status=running  -f  name=doosyapiii)" ]; then
              #docker kill doosyapiii;
              #docker rm doosyapiii;
              docker pull ${{ env.REPO }}:${{ env.VERSION }}
              docker create --name ${{ env.REPO }}_${{ env.VERSION }}  -p 5007:80 ${{ env.REPO }}:${{ env.VERSION }}
              docker start ${{ env.REPO }}_${{ env.VERSION }}
            #fi
            docker ps -a
